# Generated by Django 4.2.5 on 2023-09-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('skills', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('.NET', '.NET'), ('Testing', 'Testing'), ('Salesforce', 'Salesforce'), ('Deployment', 'Deployment'), ('DevOps', 'DevOps'), ('Cybersecurity', 'Cybersecurity'), ('DataScience', 'DataScience')], max_length=20)),
            ],
        ),
    ]
